# Generated by Django 4.2 on 2023-04-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('sizes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'my_outbound',
            },
        ),
    ]
