# Generated by Django 4.2 on 2023-04-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_outbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(choices=[('hood1', 'fancy hood'), ('hood2', 'pretty hood'), ('hood3', 'hice hood'), ('socks', 'socks'), ('jeans', 'new jeans')], default='hood1', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='write anything'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='fancy hood', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('sizes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'my_inventory',
            },
        ),
    ]
