# Generated by Django 4.2 on 2023-04-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_code_product_description_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(choices=[('hood-001', 'Super hood'), ('hood-002', 'Ultra hood'), ('hood-003', 'Super Ultra hood'), ('socks-001', 'Socks'), ('jean-001', 'Jean')], default='hood-001', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('outbound_date', models.DateTimeField(auto_now_add=True)),
                ('money', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'my_outbound',
            },
        ),
        migrations.CreateModel(
            name='Invetory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'my_inventory',
            },
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('inbound_date', models.DateTimeField(auto_now_add=True)),
                ('money', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'my_inbound',
            },
        ),
    ]
