# Generated by Django 4.2 on 2023-04-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_product_code_alter_product_price_outbound_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invetory',
            name='num',
        ),
        migrations.AddField(
            model_name='invetory',
            name='num_in',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.inbound'),
        ),
        migrations.AddField(
            model_name='invetory',
            name='num_out',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.outbound'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
