# Generated by Django 4.2 on 2023-04-07 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_code_product_description_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='sizes',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='sizes',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='outbound',
            old_name='sizes',
            new_name='product',
        ),
        migrations.AddField(
            model_name='inbound',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbound',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_inbound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_outbound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outbound',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbound',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
