# Generated by Django 4.2 on 2023-04-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_invetory_num_invetory_num_in_invetory_num_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invetory',
            name='num_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.inbound'),
        ),
        migrations.AlterField(
            model_name='invetory',
            name='num_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.outbound'),
        ),
    ]
