# Generated by Django 4.2 on 2023-04-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_invetory_num_in_alter_invetory_num_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbound',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
