# Generated by Django 4.2 on 2023-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
